FROM node:20-alpine3.18 As development

WORKDIR /app

COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build

ENV NODE_ENV production
RUN npm ci --only=production && npm cache clean --force

FROM node:20-alpine3.18 As production
WORKDIR /app

COPY --from=development /app/dist ./dist
COPY --from=development /app/node_modules ./node_modules

CMD ["npm", "run", "start:docker:prod"]